// SPDX-License-Identifier: MIT
/* ============================================================================
   NATIVE-CURRENCY / USD PRICE SOURCES, PER CHAIN.

   GENERATED by `scripts/generate-native-feeds.mjs` — do not edit by hand.
   Regenerate with `npm run generate:nativefeeds`; `--check` fails when the ADDRESSES
   OR SCALES in this file no longer match the chain (the timestamps are expected to
   move, so they are not part of that comparison).

   WHAT IT IS FOR. The launch wizard is market-cap-first and defaults to a
   $3.5K-equivalent opening market cap on every chain (CLAUDE.md, owner decision
   2026-09-20). Turning "$3,500" into a price per token needs exactly one number per
   chain: what one unit of the chain's native currency is worth in dollars. This table
   is where that number's SOURCES live; `src/price/` is where they are read.

   HOW EVERY CHAINLINK ROW WAS ESTABLISHED. Chainlink's reference-data directory said
   which address to go and look at. Then the address itself was read: it has code,
   `decimals()` agrees with the directory, `description()` names the base asset on a
   word boundary, and `latestRoundData()` returned a positive, complete, non-future
   round inside its own heartbeat plus {@link STALE_GRACE_SECONDS}. A candidate that
   failed any of those is in `chainlinkRejections` with the reason, NOT in `chainlink`.
   The directory is trusted for which addresses to look at and for the heartbeat and
   deviation threshold, which have no on-chain counterpart. It is trusted for nothing
   else.

   HOW EVERY PYTH ROW WAS ESTABLISHED. The price-feed id was not typed from memory: it
   was found by querying Hermes' own `v2/price_feeds` for the symbol and taking the id
   whose `attributes.base` and `quote_currency` match, then read back through
   `v2/updates/price/latest` to prove the id resolves to a live, positive price. That
   is verification against Pyth's own service and is WEAKER than an on-chain read — see
   the tier note below.

   THE TIERS, AND WHY THEY ARE NOT INTERCHANGEABLE
   -----------------------------------------------
   TIER 1  Chainlink aggregator, read on chain with `eth_call`. The answer is a value
           that exists in state at a block, so it has a block number, a round id and an
           audit trail, and it is the source this repository already trusts everywhere
           else (`ChainlinkPriceBandAdapter`, `src/rwa/`).

   TIER 2  Pyth, read from the Hermes HTTP service. Hermes hands back a signed update
           that anyone COULD post on chain — nothing says anyone has. So there is no
           block, no finality and no on-chain audit trail, and a compromised or merely
           wrong HTTP response is not caught by anything downstream. Acceptable for a
           UI default a human reviews before signing; NEVER to be shown as though it
           were an on-chain reading, and never to be fed to a contract.

   TIER 3  A Latch native/stablecoin pool on our own core. UNIMPLEMENTED ON PURPOSE —
           see `src/price/pool.ts` for the reason, which is that the honest version of
           it needs a time-weighted average and a depth floor that Latch cannot supply
           today.

   TIER 4  No source. The caller defaults in NATIVE units and shows no dollars at all.
           This is a correct and expected answer for several chains and must never be
           papered over with a number from somewhere else.

   WHAT A RECORD IS NOT
   --------------------
     * NOT a promise the feed is publishing NOW. `verifiedAgeSeconds` is one reading on
       one day. Every consumer re-checks the age against `staleAfterSeconds()` at read
       time; the table is a list of addresses worth asking, not a price.
     * NOT a token address. Chainlink publishes the feed, never an ERC-20.
     * NOT interchangeable with `deployments/stockFeeds.ts`. That file is tokenised
       EQUITIES on a trading session; everything here is `marketHours: "Crypto"`, which
       is 24/7/365. The difference changes what staleness MEANS: a stale equity feed on
       a Saturday is the schedule working, a stale crypto feed at any hour is a fault.
       That is why this generator rejects a stale candidate and the stock one does not.

   THE NATIVE CURRENCY'S SYMBOL AND DECIMALS ARE NOT ON-CHAIN FACTS. There is no
   contract to ask. They come from `chainid.network/chains.json` — the source
   `scripts/harvest-rpcs.mjs` already uses — and every record carries the exact entry
   it came from in `native.source`. Where chains.json is wrong or absent for one of our
   chains, `native.inferred` is true and `native.source` says what was done instead.
   ============================================================================ */

/** Which of the four tiers an answer came from. See the header. */
export type NativeUsdTier = "chainlink-onchain" | "pyth-hermes" | "latch-pool-twap" | "none";

/**
 * Which Chainlink aggregator a row points at, when a chain publishes several.
 *
 * `canonical`  the directory path is exactly `<base>-usd`: the standard Data Feed.
 * `svr`        a Smart Value Recapture feed (`-svr`, `-shared-svr`, `-shared-svr-2`).
 *              The same price data delivered through an OEV auction, so an update can
 *              land later on chain than the standard feed's. Selected only where it is
 *              the ONLY aggregator for the pair on that chain, which today means
 *              Robinhood and Arc.
 * `other`      neither — recorded rather than guessed at.
 */
export type ChainlinkFeedVariant = "canonical" | "svr" | "other";

/** One verified Chainlink native/USD aggregator. */
export interface ChainlinkNativeFeed {
  /** The proxy a consumer calls. Never the implementation behind it. */
  readonly proxyAddress: `0x${string}`;
  /** Chainlink's second published proxy for the same feed, where there is one. */
  readonly secondaryProxyAddress: `0x${string}` | null;
  /** The directory's path slug, e.g. "eth-usd" or "eth-usd-shared-svr". */
  readonly path: string;
  readonly variant: ChainlinkFeedVariant;
  /** The directory's feed name, e.g. "ETH / USD". */
  readonly feedName: string | null;
  readonly assetName: string | null;
  /** Chainlink's trading-session profile, verbatim. "Crypto" on every row here. */
  readonly marketHours: string | null;
  /** Chainlink's own risk category: "low", "medium", "new", "deprecating". */
  readonly feedCategory: string | null;
  /** `decimals()`, READ FROM THE AGGREGATOR and cross-checked against the directory. */
  readonly decimals: number;
  /** Seconds Chainlink undertakes to publish within, even if the price does not move. */
  readonly heartbeat: number;
  /** Price move, in percent, that triggers a round before the heartbeat expires. */
  readonly thresholdPercent: number | null;
  readonly contractVersion: number | null;
  /** `description()`, read from the aggregator. This is the string that proves identity. */
  readonly description: string;
  /** Bytes of runtime code at the proxy, at verification. Non-zero proves it is not an EOA. */
  readonly codeSize: number;
  readonly verifiedRoundId: string;
  /** `latestRoundData().answer` at verification, base-10, scaled by `decimals`. */
  readonly verifiedAnswer: string;
  /** `latestRoundData().updatedAt` at verification, unix seconds. */
  readonly verifiedUpdatedAt: number;
  /** How old that round was when it was read. Always within `heartbeat` + grace, or the row would not exist. */
  readonly verifiedAgeSeconds: number;
}

/**
 * One Pyth price feed IDENTIFIER, established against Hermes' metadata endpoint.
 *
 * It is an id, not a price. `v2/price_feeds` (open, keyless, HTTP 200) was queried for the
 * symbol and this is the single entry whose `attributes.symbol` is exactly
 * `Crypto.<SYMBOL>/USD`; a query that matched more than one was refused rather than
 * resolved by picking.
 *
 * `verifiedPrice` is usually null and `priceCheck` says why: as of 2026-09-20 Hermes'
 * PRICE endpoints (`v2/updates/price/latest`, `api/latest_price_feeds`) answer
 * `401 unauthorized` without a credential, on the documented public host and on
 * hermes-beta alike. Only the metadata endpoint is still keyless. So an off-chain Hermes
 * read is not a route this SDK can take without a key, and tier 2 reads the Pyth CONTRACT
 * on chain instead — see `src/price/pyth.ts`.
 */
export interface PythNativeFeed {
  /** Pyth's 32-byte price-feed id, `0x`-prefixed. This is the part that was verified. */
  readonly priceFeedId: `0x${string}`;
  /** Hermes' own symbol for the feed, e.g. "Crypto.ETH/USD". The string that was matched. */
  readonly hermesSymbol: string | null;
  readonly displaySymbol: string | null;
  readonly description: string | null;
  /** What happened when a price read was attempted: "read and sane", or the failure. */
  readonly priceCheck: string;
  /** `price.price` at verification, base-10, scaled by `10 ** verifiedExpo`. Null when unread. */
  readonly verifiedPrice: string | null;
  /** `price.expo`, negative in practice. Null when unread. */
  readonly verifiedExpo: number | null;
  readonly verifiedPublishTime: number | null;
  readonly verifiedAgeSeconds: number | null;
}

/** A candidate that was read and REFUSED, with the reason, so a diff shows what changed. */
export interface ChainlinkNativeFeedRejection {
  readonly proxyAddress: `0x${string}`;
  readonly path: string;
  readonly feedName: string | null;
  readonly decimals: number;
  readonly heartbeat: number;
  readonly reason: string;
}

/** What the chain's native currency is. NOT an on-chain fact — see the header. */
export interface NativeCurrencyFact {
  readonly symbol: string;
  readonly decimals: number;
  /** True when the value could not be read for this chain id and was taken from elsewhere. */
  readonly inferred: boolean;
  /** Exactly where it came from, quoted, so a wrong one is arguable rather than mysterious. */
  readonly source: string;
}

/** One chain's whole native/USD survey: what exists, what was refused, and why. */
export interface NativeFeedRecord {
  readonly chainId: number;
  readonly chainKey: string;
  readonly chainName: string;
  readonly testnet: boolean;
  readonly native: NativeCurrencyFact;
  /** The selected tier-1 source, or `null` when the chain has none. */
  readonly chainlink: ChainlinkNativeFeed | null;
  /** Other VERIFIED aggregators for the same pair, not selected. Kept so the choice is auditable. */
  readonly chainlinkAlternatives: readonly ChainlinkNativeFeed[];
  readonly chainlinkRejections: readonly ChainlinkNativeFeedRejection[];
  /** The tier-2 source, or `null`. Probed on every chain, not only the ones Chainlink misses. */
  readonly pyth: PythNativeFeed | null;
  /** Why there is no Pyth row, when there is none. */
  readonly pythRejection: string | null;
  /** Why there is no Chainlink row, when there is none. */
  readonly note: string | null;
  readonly directoryUrl: string | null;
  /** The RPC endpoint that answered the verification reads. */
  readonly verifiedEndpoint: string | null;
}

/** When the table below was produced. Every `verified*` number is one reading at this instant. */
export const NATIVE_FEEDS_VERIFIED_AT = "2026-09-21T00:47:14.328Z";

/** The same instant as a unix second, so an age can be recomputed without parsing a string. */
export const NATIVE_FEEDS_VERIFIED_INSTANT = 1789951634;

/** Chainlink's reference-data directory, the document the addresses came from. */
export const NATIVE_FEED_DIRECTORY_BASE = "https://reference-data-directory.vercel.app";

/** Pyth's Hermes service, the endpoint the tier-2 ids and prices came from. */
export const PYTH_HERMES_BASE = "https://hermes.pyth.network";

/**
 * Grace added to a feed's own heartbeat before an answer is called stale, in seconds.
 *
 * `updatedAt` is the timestamp of the block that INCLUDED the update, not of the
 * observation, so a feed publishing exactly on its heartbeat can still read a little over
 * it through block-time jitter and sequencer timestamp latitude. Five minutes absorbs that
 * on every chain here and is negligible against a 3,600 s or 86,400 s heartbeat; against
 * BNB's 27 s heartbeat the grace dominates, which is correct — one missed 27-second beat
 * is noise, not a fault.
 *
 * The generator applies exactly this constant when it decides whether to ship a feed, so
 * the committed table and the runtime reader cannot drift apart.
 */
export const STALE_GRACE_SECONDS = 300;

/** Every chain that was surveyed, whether or not a source was found. */
export const NATIVE_FEEDS: Readonly<Record<number, NativeFeedRecord>> = {
  1: {
    chainId: 1,
    chainKey: "ethereum",
    chainName: "Ethereum",
    testnet: false,
    native: {
      symbol: "ETH",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 1 (Ethereum Mainnet), nativeCurrency {\"name\":\"Ether\",\"symbol\":\"ETH\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419",
      secondaryProxyAddress: null,
      path: "eth-usd",
      variant: "canonical",
      feedName: "ETH / USD",
      assetName: "Ethereum",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 3600,
      thresholdPercent: 0.5,
      contractVersion: 6,
      description: "ETH / USD",
      codeSize: 9571,
      verifiedRoundId: "129127208515966895171",
      verifiedAnswer: "269442899628",
      verifiedUpdatedAt: 1789950107,
      verifiedAgeSeconds: 1527,
    },
    chainlinkAlternatives: [
      {
        proxyAddress: "0x5147eA642CAEF7BD9c1265AadcA78f997AbB9649",
        secondaryProxyAddress: "0x5424384B256154046E9667dDFaaa5e550145215e",
        path: "eth-usd-svr",
        variant: "svr",
        feedName: "ETH / USD",
        assetName: "Ethereum",
        marketHours: "Crypto",
        feedCategory: "low",
        decimals: 8,
        heartbeat: 3600,
        thresholdPercent: 0.5,
        contractVersion: 6,
        description: "ETH / USD",
        codeSize: 9571,
        verifiedRoundId: "18446744073709575751",
        verifiedAnswer: "269501241270",
        verifiedUpdatedAt: 1789950095,
        verifiedAgeSeconds: 1539,
      },
      {
        proxyAddress: "0xd82562bb17557231Cd871e1B2525F3AB8d63D409",
        secondaryProxyAddress: "0xc0053f3FBcCD593758258334Dfce24C2A9A673aD",
        path: "eth-usd-shared-svr",
        variant: "svr",
        feedName: "ETH / USD",
        assetName: "Ethereum",
        marketHours: "Crypto",
        feedCategory: "low",
        decimals: 8,
        heartbeat: 3600,
        thresholdPercent: 0.5,
        contractVersion: 6,
        description: "ETH / USD",
        codeSize: 9571,
        verifiedRoundId: "18446744073709569261",
        verifiedAnswer: "268402146798",
        verifiedUpdatedAt: 1789949771,
        verifiedAgeSeconds: 1863,
      },
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace",
      hermesSymbol: "Crypto.ETH/USD",
      displaySymbol: "ETHUSD",
      description: "ETHEREUM / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-mainnet.json",
    verifiedEndpoint: "https://1.rpc.thirdweb.com",
  },
  56: {
    chainId: 56,
    chainKey: "bsc",
    chainName: "BNB Smart Chain",
    testnet: false,
    native: {
      symbol: "BNB",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 56 (BNB Smart Chain Mainnet), nativeCurrency {\"name\":\"BNB Chain Native Token\",\"symbol\":\"BNB\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE",
      secondaryProxyAddress: null,
      path: "bnb-usd",
      variant: "canonical",
      feedName: "BNB / USD",
      assetName: "BNB",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 27,
      thresholdPercent: 0.1,
      contractVersion: 6,
      description: "BNB / USD",
      codeSize: 9571,
      verifiedRoundId: "55340232221132102768",
      verifiedAnswer: "78134890000",
      verifiedUpdatedAt: 1789951619,
      verifiedAgeSeconds: 15,
    },
    chainlinkAlternatives: [
      {
        proxyAddress: "0xd5D290Fe2ae6b55F385ab9C14d2CeB91DD3d9022",
        secondaryProxyAddress: "0xA59395678BB6a010a7206f46b6dab8A1e7aC7221",
        path: "bnb-usd-shared-svr",
        variant: "svr",
        feedName: "BNB / USD",
        assetName: "BNB",
        marketHours: "Crypto",
        feedCategory: "low",
        decimals: 18,
        heartbeat: 27,
        thresholdPercent: 0.1,
        contractVersion: 6,
        description: "BNB / USD",
        codeSize: 9571,
        verifiedRoundId: "18446744073710323863",
        verifiedAnswer: "780876530000000000000",
        verifiedUpdatedAt: 1789951611,
        verifiedAgeSeconds: 23,
      },
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0x2f95862b045670cd22bee3114c39763a4a08beeb663b145d283c31d7d1101c4f",
      hermesSymbol: "Crypto.BNB/USD",
      displaySymbol: "BNBUSD",
      description: "BNB / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-bsc-mainnet.json",
    verifiedEndpoint: "https://56.rpc.thirdweb.com",
  },
  8453: {
    chainId: 8453,
    chainKey: "base",
    chainName: "Base",
    testnet: false,
    native: {
      symbol: "ETH",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 8453 (Base), nativeCurrency {\"name\":\"Ether\",\"symbol\":\"ETH\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x50015f8b17fb2C290Dde41fDc246ed0dcEE93a8b",
      secondaryProxyAddress: "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70",
      path: "eth-usd-shared-svr-2",
      variant: "svr",
      feedName: "ETH / USD",
      assetName: "Ethereum",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 1200,
      thresholdPercent: 0.15,
      contractVersion: 6,
      description: "ETH / USD",
      codeSize: 9571,
      verifiedRoundId: "18446744073709556026",
      verifiedAnswer: "269579082546",
      verifiedUpdatedAt: 1789951587,
      verifiedAgeSeconds: 47,
    },
    chainlinkAlternatives: [
      {
        proxyAddress: "0xa4250cE1aA15Ff4cb5E5a8655293b65694e436Ed",
        secondaryProxyAddress: "0x9dA00D23465282005DB222a441a663eE7B9dfCc8",
        path: "eth-usd-svr",
        variant: "svr",
        feedName: "ETH / USD",
        assetName: "Ethereum",
        marketHours: "Crypto",
        feedCategory: "low",
        decimals: 8,
        heartbeat: 1200,
        thresholdPercent: 0.15,
        contractVersion: 6,
        description: "ETH / USD",
        codeSize: 9571,
        verifiedRoundId: "18446744073709632407",
        verifiedAnswer: "269570616817",
        verifiedUpdatedAt: 1789951589,
        verifiedAgeSeconds: 45,
      },
      {
        proxyAddress: "0x5731Ae06077c79A3B292498940211E0aE7130bd3",
        secondaryProxyAddress: "0x1428C9E908e32dD2839F99D63C242c91329A58C0",
        path: "eth-usd-shared-svr",
        variant: "svr",
        feedName: "ETH / USD",
        assetName: "Ethereum",
        marketHours: "Crypto",
        feedCategory: "low",
        decimals: 18,
        heartbeat: 1200,
        thresholdPercent: 0.15,
        contractVersion: 6,
        description: "ETH / USD",
        codeSize: 9571,
        verifiedRoundId: "18446744073709610737",
        verifiedAnswer: "2696428035090000000000",
        verifiedUpdatedAt: 1789951593,
        verifiedAgeSeconds: 41,
      },
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace",
      hermesSymbol: "Crypto.ETH/USD",
      displaySymbol: "ETHUSD",
      description: "ETHEREUM / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-base-1.json",
    verifiedEndpoint: "https://8453.rpc.thirdweb.com",
  },
  4663: {
    chainId: 4663,
    chainKey: "robinhood",
    chainName: "Robinhood Chain",
    testnet: false,
    native: {
      symbol: "ETH",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 4663 (Robinhood Chain), nativeCurrency {\"name\":\"Ether\",\"symbol\":\"ETH\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x78F3556b67E17Df817D51Ef5a990cDaF09E8d3A9",
      secondaryProxyAddress: "0x5058aDee53b04e374d8bEDbAD634Bc4778F50b22",
      path: "eth-usd-shared-svr",
      variant: "svr",
      feedName: "ETH / USD",
      assetName: "Ethereum",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 86400,
      thresholdPercent: 0.5,
      contractVersion: 6,
      description: "ETH / USD",
      codeSize: 9571,
      verifiedRoundId: "18446744073709553929",
      verifiedAnswer: "269695646709",
      verifiedUpdatedAt: 1789951599,
      verifiedAgeSeconds: 35,
    },
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace",
      hermesSymbol: "Crypto.ETH/USD",
      displaySymbol: "ETHUSD",
      description: "ETHEREUM / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-robinhood-mainnet.json",
    verifiedEndpoint: "https://rpc.mainnet.chain.robinhood.com",
  },
  57073: {
    chainId: 57073,
    chainKey: "ink",
    chainName: "Ink",
    testnet: false,
    native: {
      symbol: "ETH",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 57073 (Ink), nativeCurrency {\"name\":\"Ether\",\"symbol\":\"ETH\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x963d5d3aD2Dfd3fe759d376fF62A0963176DBdF5",
      secondaryProxyAddress: "0xcc2cBeC935a472B01c9d791c22056C2D6E7E86ef",
      path: "eth-usd",
      variant: "canonical",
      feedName: "ETH / USD",
      assetName: "Ethereum",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 3600,
      thresholdPercent: 0.1,
      contractVersion: 6,
      description: "ETH / USD",
      codeSize: 9571,
      verifiedRoundId: "18446744073709564033",
      verifiedAnswer: "269830698475",
      verifiedUpdatedAt: 1789951595,
      verifiedAgeSeconds: 39,
    },
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace",
      hermesSymbol: "Crypto.ETH/USD",
      displaySymbol: "ETHUSD",
      description: "ETHEREUM / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-ink-1.json",
    verifiedEndpoint: "https://ink.drpc.org",
  },
  59144: {
    chainId: 59144,
    chainKey: "linea",
    chainName: "Linea",
    testnet: false,
    native: {
      symbol: "ETH",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 59144 (Linea), nativeCurrency {\"name\":\"Linea Ether\",\"symbol\":\"ETH\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x3c6Cd9Cc7c7a4c2Cf5a82734CD249D7D593354dA",
      secondaryProxyAddress: null,
      path: "eth-usd",
      variant: "canonical",
      feedName: "ETH / USD",
      assetName: "Ethereum",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 86400,
      thresholdPercent: 0.5,
      contractVersion: 4,
      description: "ETH / USD",
      codeSize: 9571,
      verifiedRoundId: "18446744073709586016",
      verifiedAnswer: "269159000000",
      verifiedUpdatedAt: 1789950031,
      verifiedAgeSeconds: 1603,
    },
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace",
      hermesSymbol: "Crypto.ETH/USD",
      displaySymbol: "ETHUSD",
      description: "ETHEREUM / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-linea-1.json",
    verifiedEndpoint: "https://linea.drpc.org",
  },
  196: {
    chainId: 196,
    chainKey: "xlayer",
    chainName: "X Layer",
    testnet: false,
    native: {
      symbol: "OKB",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 196 (X Layer Mainnet), nativeCurrency {\"name\":\"X Layer Global Utility Token\",\"symbol\":\"OKB\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x4Ff345b18a2bF894F8627F41501FBf30d5C5e7BE",
      secondaryProxyAddress: null,
      path: "okb-usd",
      variant: "canonical",
      feedName: "OKB / USD",
      assetName: "OKB",
      marketHours: "Crypto",
      feedCategory: "medium",
      decimals: 8,
      heartbeat: 86400,
      thresholdPercent: 0.5,
      contractVersion: 6,
      description: "OKB / USD",
      codeSize: 9571,
      verifiedRoundId: "18446744073709578447",
      verifiedAnswer: "11861502000",
      verifiedUpdatedAt: 1789949592,
      verifiedAgeSeconds: 2042,
    },
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xd6f83dfeaff95d596ddec26af2ee32f391c206a183b161b7980821860eeef2f5",
      hermesSymbol: "Crypto.OKB/USD",
      displaySymbol: "OKBUSD",
      description: "OKB / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-xlayer-1.json",
    verifiedEndpoint: "https://xlayer.drpc.org",
  },
  999: {
    chainId: 999,
    chainKey: "hyperevm",
    chainName: "HyperEVM",
    testnet: false,
    native: {
      symbol: "HYPE",
      decimals: 18,
      inferred: true,
      source: "chains.json id 999 is WANCHAIN TESTNET, not HyperEVM — the same collision scripts/harvest-rpcs.mjs guards against. HyperEVM mainnet is absent from chains.json entirely. Symbol and decimals taken from chains.json id 998 (Hyperliquid EVM Testnet, nativeCurrency {\"name\":\"HYPE\",\"symbol\":\"HYPE\",\"decimals\":18}), which is the same VM and the same gas asset. THIS IS AN INFERENCE, not a reading of chain 999.",
    },
    chainlink: {
      proxyAddress: "0xa5a72eF19F82A579431186402425593a559ed352",
      secondaryProxyAddress: null,
      path: "hype-usd",
      variant: "canonical",
      feedName: "HYPE / USD",
      assetName: "Hyperliquid",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 86400,
      thresholdPercent: 0.5,
      contractVersion: 6,
      description: "HYPE / USD",
      codeSize: 9571,
      verifiedRoundId: "18446744073709576963",
      verifiedAnswer: "9396967900",
      verifiedUpdatedAt: 1789949143,
      verifiedAgeSeconds: 2491,
    },
    chainlinkAlternatives: [
      {
        proxyAddress: "0x2b25BC41D55de29F3A2e163F8Eebf63966B25b57",
        secondaryProxyAddress: "0x2c031aC5cf6C48481897ed5a4E573de8662c8D34",
        path: "hype-usd-shared-svr",
        variant: "svr",
        feedName: "HYPE / USD",
        assetName: "Hyperliquid",
        marketHours: "Crypto",
        feedCategory: "low",
        decimals: 18,
        heartbeat: 86400,
        thresholdPercent: 0.5,
        contractVersion: 6,
        description: "HYPE / USD",
        codeSize: 9571,
        verifiedRoundId: "18446744073709567555",
        verifiedAnswer: "94125707000000000000",
        verifiedUpdatedAt: 1789949644,
        verifiedAgeSeconds: 1990,
      },
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0x4279e31cc369bbcc2faf022b382b080e32a8e689ff20fbc530d2a603eb6cd98b",
      hermesSymbol: "Crypto.HYPE/USD",
      displaySymbol: "HYPEUSD",
      description: "HYPERLIQUID / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-hyperliquid-mainnet.json",
    verifiedEndpoint: "https://rpc.purroofgroup.com",
  },
  143: {
    chainId: 143,
    chainKey: "monad",
    chainName: "Monad",
    testnet: false,
    native: {
      symbol: "MON",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 143 (Monad), nativeCurrency {\"name\":\"Monad\",\"symbol\":\"MON\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0xBcD78f76005B7515837af6b50c7C52BCf73822fb",
      secondaryProxyAddress: null,
      path: "mon-usd",
      variant: "canonical",
      feedName: "MON / USD",
      assetName: "Monad",
      marketHours: "Crypto",
      feedCategory: "new",
      decimals: 8,
      heartbeat: 3600,
      thresholdPercent: 0.02,
      contractVersion: 6,
      description: "MON / USD",
      codeSize: 9571,
      verifiedRoundId: "18446744073710125098",
      verifiedAnswer: "2532701",
      verifiedUpdatedAt: 1789951600,
      verifiedAgeSeconds: 34,
    },
    chainlinkAlternatives: [
      {
        proxyAddress: "0xFB504aD06Ab5E6c63FE0A46FEa245214838E8015",
        secondaryProxyAddress: "0x432AAcD32253B6683f6483fB0d3285bA0082EfDb",
        path: "mon-usd-shared-svr",
        variant: "svr",
        feedName: "MON / USD",
        assetName: "Monad",
        marketHours: "Crypto",
        feedCategory: "new",
        decimals: 18,
        heartbeat: 3600,
        thresholdPercent: 0.05,
        contractVersion: 6,
        description: "MON / USD",
        codeSize: 9571,
        verifiedRoundId: "18446744073709737180",
        verifiedAnswer: "25330000000000000",
        verifiedUpdatedAt: 1789951611,
        verifiedAgeSeconds: 23,
      },
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0x31491744e2dbf6df7fcf4ac0820d18a609b49076d45066d3568424e62f686cd1",
      hermesSymbol: "Crypto.MON/USD",
      displaySymbol: "MONUSD",
      description: "MONAD / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-monad-mainnet.json",
    verifiedEndpoint: "https://rpc.monad.xyz",
  },
  9745: {
    chainId: 9745,
    chainKey: "plasma",
    chainName: "Plasma",
    testnet: false,
    native: {
      symbol: "XPL",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 9745 (Plasma Mainnet), nativeCurrency {\"name\":\"Plasma\",\"symbol\":\"XPL\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0xF932477C37715aE6657Ab884414Bd9876FE3f750",
      secondaryProxyAddress: null,
      path: "xpl-usd",
      variant: "canonical",
      feedName: "XPL / USD",
      assetName: "Plasma",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 86400,
      thresholdPercent: 0.5,
      contractVersion: 6,
      description: "XPL / USD",
      codeSize: 9571,
      verifiedRoundId: "18446744073709595631",
      verifiedAnswer: "9112273",
      verifiedUpdatedAt: 1789951551,
      verifiedAgeSeconds: 83,
    },
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0x9873512f5cb33c77ad7a5af098d74812c62111166be395fd0941c8cedb9b00d4",
      hermesSymbol: "Crypto.XPL/USD",
      displaySymbol: "XPLUSD",
      description: "PLASMA / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-plasma-mainnet.json",
    verifiedEndpoint: "https://rpc.plasma.to",
  },
  988: {
    chainId: 988,
    chainKey: "stable",
    chainName: "Stable",
    testnet: false,
    native: {
      symbol: "USDT0",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 988 (Stable Mainnet), nativeCurrency {\"name\":\"USDT0\",\"symbol\":\"USDT0\",\"decimals\":18}",
    },
    chainlink: null,
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xcfc1303ea9f083b1b4f99e1369fb9d2611f3230d5ea33a6abf2f86071c089fdc",
      hermesSymbol: "Crypto.USDT0/USD",
      displaySymbol: "USDT0USD",
      description: "USDT0 / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: "no Chainlink directory document for this chain (HTTP 404) — Stable's native gas asset is USDT0, which is NOT USDT: pricing one with the other's feed asserts a peg this SDK has not verified, so no USDT/USD feed is substituted here. Pyth does publish a distinct Crypto.USDT0/USD feed and its id is recorded above, but reading it needs a Pyth contract address on chain 988 that this run did not verify, so Stable resolves at tier 4 today — launches there default in native units, which is the correct answer rather than a gap. Verify a Pyth contract on 988 to promote it to tier 2.",
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-stable-mainnet.json",
    verifiedEndpoint: null,
  },
  5042: {
    chainId: 5042,
    chainKey: "arc",
    chainName: "Arc",
    testnet: false,
    native: {
      symbol: "USDC",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 5042 (Arc), nativeCurrency {\"name\":\"USDC\",\"symbol\":\"USDC\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x84EA90AC252Dc437031461836DB5164219147905",
      secondaryProxyAddress: "0xBC88A5182848151AE1f7b4877021F828d8F4D735",
      path: "usdc-usd-shared-svr",
      variant: "svr",
      feedName: "USDC / USD",
      assetName: "Circle USD",
      marketHours: "Crypto",
      feedCategory: "low",
      decimals: 8,
      heartbeat: 86400,
      thresholdPercent: 0.5,
      contractVersion: 6,
      description: "USDC / USD",
      codeSize: 9571,
      verifiedRoundId: "36893488147419103291",
      verifiedAnswer: "99988744",
      verifiedUpdatedAt: 1789917428,
      verifiedAgeSeconds: 34206,
    },
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a",
      hermesSymbol: "Crypto.USDC/USD",
      displaySymbol: "USDCUSD",
      description: "USD COIN / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: null,
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-arc-mainnet.json",
    verifiedEndpoint: "https://rpc.mainnet.arc.io",
  },
  11155111: {
    chainId: 11155111,
    chainKey: "sepolia",
    chainName: "Ethereum Sepolia",
    testnet: true,
    native: {
      symbol: "ETH",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 11155111 (Ethereum Sepolia), nativeCurrency {\"name\":\"Sepolia Ether\",\"symbol\":\"ETH\",\"decimals\":18}",
    },
    chainlink: {
      proxyAddress: "0x694AA1769357215DE4FAC081bf1f309aDC325306",
      secondaryProxyAddress: null,
      path: "eth-usd",
      variant: "canonical",
      feedName: "ETH / USD",
      assetName: null,
      marketHours: "Crypto",
      feedCategory: null,
      decimals: 8,
      heartbeat: 3600,
      thresholdPercent: 1,
      contractVersion: 4,
      description: "ETH / USD",
      codeSize: 6992,
      verifiedRoundId: "18446744073709587825",
      verifiedAnswer: "268291890239",
      verifiedUpdatedAt: 1789949688,
      verifiedAgeSeconds: 1946,
    },
    chainlinkAlternatives: [
      {
        proxyAddress: "0xD9d6f482B88C43B256fD481826890dffC8544B13",
        secondaryProxyAddress: null,
        path: "eth-usd-nops",
        variant: "other",
        feedName: "ETH / USD",
        assetName: null,
        marketHours: "Crypto",
        feedCategory: null,
        decimals: 8,
        heartbeat: 3600,
        thresholdPercent: 1,
        contractVersion: 4,
        description: "ETH / USD",
        codeSize: 9571,
        verifiedRoundId: "18446744073709577579",
        verifiedAnswer: "267346596993",
        verifiedUpdatedAt: 1789949616,
        verifiedAgeSeconds: 2018,
      },
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace",
      hermesSymbol: "Crypto.ETH/USD",
      displaySymbol: "ETHUSD",
      description: "ETHEREUM / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: "Sepolia's Chainlink ETH/USD feed prices REAL ether, not Sepolia ether, which has no market price at all. The feed is recorded because it exists and was verified; the resolver refuses to spend it on a USD figure for a testnet unless a caller opts in.",
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia.json",
    verifiedEndpoint: "https://11155111.rpc.thirdweb.com",
  },
  2201: {
    chainId: 2201,
    chainKey: "stableTestnet",
    chainName: "Stable Testnet",
    testnet: true,
    native: {
      symbol: "USDT0",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 2201 (Stable Testnet), nativeCurrency {\"name\":\"USDT0\",\"symbol\":\"USDT0\",\"decimals\":18}",
    },
    chainlink: null,
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xcfc1303ea9f083b1b4f99e1369fb9d2611f3230d5ea33a6abf2f86071c089fdc",
      hermesSymbol: "Crypto.USDT0/USD",
      displaySymbol: "USDT0USD",
      description: "USDT0 / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: "no Chainlink directory document for this chain (HTTP 404) — Same as chain 988: the native asset is USDT0, and the Pyth id is recorded but unusable without a verified Pyth contract on this chain.",
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-stable-testnet.json",
    verifiedEndpoint: null,
  },
  5042002: {
    chainId: 5042002,
    chainKey: "arcTestnet",
    chainName: "Arc Testnet",
    testnet: true,
    native: {
      symbol: "USDC",
      decimals: 18,
      inferred: false,
      source: "chainid.network/chains.json id 5042002 (Arc Network Testnet), nativeCurrency {\"name\":\"USDC\",\"symbol\":\"USDC\",\"decimals\":18}",
    },
    chainlink: null,
    chainlinkAlternatives: [
    ],
    chainlinkRejections: [
    ],
    pyth: {
      priceFeedId: "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a",
      hermesSymbol: "Crypto.USDC/USD",
      displaySymbol: "USDCUSD",
      description: "USD COIN / US DOLLAR",
      priceCheck: "v2/updates/price/latest returned HTTP 401 (unauthorized — this endpoint is no longer keyless)",
      verifiedPrice: null,
      verifiedExpo: null,
      verifiedPublishTime: null,
      verifiedAgeSeconds: null,
    },
    pythRejection: null,
    note: "no Chainlink directory document for this chain (HTTP 404) — Arc Testnet publishes no Chainlink directory document (HTTP 404 on 2026-09-20).",
    directoryUrl: "https://reference-data-directory.vercel.app/feeds-arc-testnet.json",
    verifiedEndpoint: null,
  },
};

/** Every chain this survey covers, whether or not it found anything. */
export const NATIVE_FEED_CHAIN_IDS: readonly number[] = Object.values(NATIVE_FEEDS)
  .map((r) => r.chainId)
  .sort((a, b) => a - b);

/**
 * Chain ids the SDK can price UNAIDED — a verified Chainlink aggregator it can read with
 * nothing but an RPC endpoint. This is the only list a caller should treat as "we have a
 * price here": a Pyth id is an identifier, not a reachable source, until somebody supplies
 * a verified Pyth contract address for that chain.
 */
export const NATIVE_USD_TIER1_CHAIN_IDS: readonly number[] = Object.values(NATIVE_FEEDS)
  .filter((r) => r.chainlink !== null)
  .map((r) => r.chainId)
  .sort((a, b) => a - b);

/**
 * Chain ids with a verified Pyth price-feed ID and no Chainlink aggregator. Reaching the
 * price still needs a Pyth contract address on that chain, which this survey does NOT
 * supply — see `src/price/pyth.ts`.
 */
export const NATIVE_USD_PYTH_ONLY_CHAIN_IDS: readonly number[] = Object.values(NATIVE_FEEDS)
  .filter((r) => r.chainlink === null && r.pyth !== null)
  .map((r) => r.chainId)
  .sort((a, b) => a - b);

/** Chain ids that were surveyed and where nothing at all was found. */
export const NATIVE_USD_NO_SOURCE_CHAIN_IDS: readonly number[] = Object.values(NATIVE_FEEDS)
  .filter((r) => r.chainlink === null && r.pyth === null)
  .map((r) => r.chainId)
  .sort((a, b) => a - b);

/** The survey row for `chainId`; `undefined` when the chain was never surveyed. */
export function nativeFeedFor(chainId: number): NativeFeedRecord | undefined {
  return NATIVE_FEEDS[chainId];
}

/**
 * When an answer from `feed` stops being usable, in seconds of age.
 *
 * The feed's own published heartbeat plus {@link STALE_GRACE_SECONDS}. It is the feed's
 * number, not ours: a consumer that picks its own threshold is picking a number the
 * publisher never agreed to.
 */
export function staleAfterSeconds(feed: ChainlinkNativeFeed): number {
  return feed.heartbeat + STALE_GRACE_SECONDS;
}
